<?php

namespace Database\Seeders;

use App\Models\Form;
use Illuminate\Database\Seeder;

class FormSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fields = [
            [#4254
                "id"       => 1,
                "name"     => "Nombres y Apellidos",
                "type"     => "text",
                "required" => true,
                "size"     => "col-xs-12 col-sm-6 col-md-6 col-lg-6",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "nombres-y-apellidos",
            ],
            [#4253
                "id"       => 2,
                "name"     => "Edad",
                "type"     => "number",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "edad",
            ],
            [#4252
                "id"       => 3,
                "name"     => "Sexo",
                "type"     => "select",
                "required" => true,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [
                    [#4251
                        "id"       => 1,
                        "name"     => "M",
                        "value"    => "m-1",
                        "order"    => 1,
                        "editMode" => false,
                    ],
                    [#4250
                        "id"       => 2,
                        "name"     => "F",
                        "value"    => "f-2",
                        "order"    => 2,
                        "editMode" => false,
                    ],
                ],
                "slug"     => "sexo",
            ],
            [#4249
                "id"       => 4,
                "name"     => "Fecha de Nacimiento",
                "type"     => "date",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "fecha-de-nacimiento",
            ],
            [#4248
                "id"       => 5,
                "name"     => "Cédula de Identidad",
                "type"     => "text",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "cedula-de-identidad",
            ],
            [#4247
                "id"       => 6,
                "name"     => "Tipo de Discapacidad o alteración en el desarrollo",
                "type"     => "select multiple",
                "required" => true,
                "size"     => "col-xs-12 col-sm-6 col-md-6 col-lg-6",
                "tab_id"   => "1",
                "options"  => [
                    [
                        "id"       => 1,
                        "name"     => "Sin Discapacidad",
                        "value"    => "sin-discapacidad-1",
                        "order"    => 1,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 2,
                        "name"     => "Sindrome Kabiki",
                        "value"    => "sindrome-kabiki-2",
                        "order"    => 2,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 3,
                        "name"     => "Intelectual",
                        "value"    => "intelectual-3",
                        "order"    => 3,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 4,
                        "name"     => "Visual",
                        "value"    => "visual-4",
                        "order"    => 4,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 5,
                        "name"     => "Parálisis Cerebral",
                        "value"    => "paralisis-cerebral-5",
                        "order"    => 5,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 6,
                        "name"     => "Auditiva",
                        "value"    => "auditiva-6",
                        "order"    => 6,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 7,
                        "name"     => "Motora",
                        "value"    => "motora-7",
                        "order"    => 7,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 8,
                        "name"     => "Psicosocial",
                        "value"    => "psicosocial-8",
                        "order"    => 8,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 9,
                        "name"     => "Fisico motora",
                        "value"    => "fisico-motora-9",
                        "order"    => 9,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 10,
                        "name"     => "Déficit de atención",
                        "value"    => "deficit-de-atencion--10",
                        "order"    => 10,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 11,
                        "name"     => "Parálisis Cerebral Infantil",
                        "value"    => "paralisis-cerebral-infantil-11",
                        "order"    => 11,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 12,
                        "name"     => "Alteración En el desarrollo",
                        "value"    => "alteracion-en-el-desarrollo-12",
                        "order"    => 12,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 13,
                        "name"     => "Retardo en el Desarrollo Sicomotor",
                        "value"    => "retardo-en-el-desarrollo-sicomotor-13",
                        "order"    => 13,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 14,
                        "name"     => "Paladar Hendido",
                        "value"    => "paladar-hendido-14",
                        "order"    => 14,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 15,
                        "name"     => "Pie equinovaro",
                        "value"    => "pie-equinovaro-15",
                        "order"    => 15,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 16,
                        "name"     => "Microcefalia Severa",
                        "value"    => "microcefalia-severa-16",
                        "order"    => 16,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 17,
                        "name"     => "Trastorno en el Lenguaje",
                        "value"    => "trastorno-en-el-lenguaje-17",
                        "order"    => 17,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 18,
                        "name"     => "Intelectual Leve",
                        "value"    => "intelectual-leve-18",
                        "order"    => 18,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 19,
                        "name"     => "Microcefalia",
                        "value"    => "microcefalia-19",
                        "order"    => 19,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 20,
                        "name"     => "Sindrome de Down",
                        "value"    => "sindrome-de-down-20",
                        "order"    => 20,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 21,
                        "name"     => "Autismo",
                        "value"    => "autismo-21",
                        "order"    => 21,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 22,
                        "name"     => "Hipotoridome congénito",
                        "value"    => "hipotoridome-congenito-22",
                        "order"    => 22,
                        "editMode" => false,
                    ]
                ],
                "slug"     => "tipo-de-discapacidad-o-alteracion-en-el-desarrollo",
            ],
            [#4276
                "id"       => 7,
                "name"     => "Dirección",
                "type"     => "text",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-6 col-lg-6",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "direccion",
            ],
            [#4277
                "id"       => 8,
                "name"     => "Barrio",
                "type"     => "text",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "barrio",
            ],
            [#4278
                "id"       => 9,
                "name"     => "Municipio",
                "type"     => "text",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "municipio",
            ],
            [
                "id"       => 10,
                "name"     => "Departamento",
                "type"     => "select",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [
                    [
                        "id"       => 1,
                        "name"     => "Chinandega",
                        "value"    => "chinandega-1",
                        "order"    => 1,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 2,
                        "name"     => "León",
                        "value"    => "leon-2",
                        "order"    => 2,
                        "editMode" => false,
                    ],
                    [#4282
                        "id"       => 3,
                        "name"     => "Managua",
                        "value"    => "managua-3",
                        "order"    => 3,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 4,
                        "name"     => "Masaya",
                        "value"    => "masaya-4",
                        "order"    => 4,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 5,
                        "name"     => "Carazo",
                        "value"    => "carazo-5",
                        "order"    => 5,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 6,
                        "name"     => "Granada",
                        "value"    => "granada-6",
                        "order"    => 6,
                        "editMode" => false,
                    ],
                    [
                        "id"       => 7,
                        "name"     => "Rivas",
                        "value"    => "rivas-7",
                        "order"    => 7,
                        "editMode" => false,
                    ],
                    [#4287
                        "id"       => 8,
                        "name"     => "Nueva Segovia",
                        "value"    => "nueva-segovia-8",
                        "order"    => 8,
                        "editMode" => false,
                    ],
                    [#4288
                        "id"       => 9,
                        "name"     => "Madriz",
                        "value"    => "madriz-9",
                        "order"    => 9,
                        "editMode" => false,
                    ],
                    [#4289
                        "id"       => 10,
                        "name"     => "Estelí",
                        "value"    => "esteli-10",
                        "order"    => 10,
                        "editMode" => false,
                    ],
                    [#4290
                        "id"       => 11,
                        "name"     => "Jinotega",
                        "value"    => "jinotega-11",
                        "order"    => 11,
                        "editMode" => false,
                    ],
                    [#4291
                        "id"       => 12,
                        "name"     => "Matagalpa",
                        "value"    => "matagalpa-12",
                        "order"    => 12,
                        "editMode" => false,
                    ],
                    [#4292
                        "id"       => 13,
                        "name"     => "Boaco",
                        "value"    => "boaco-13",
                        "order"    => 13,
                        "editMode" => false,
                    ],
                    [#4293
                        "id"       => 14,
                        "name"     => "Chontales",
                        "value"    => "chontales-14",
                        "order"    => 14,
                        "editMode" => false,
                    ],
                    [#4294
                        "id"       => 15,
                        "name"     => "Río San Juan",
                        "value"    => "rio-san-juan-15",
                        "order"    => 15,
                        "editMode" => false,
                    ],
                    [#4295
                        "id"       => 16,
                        "name"     => "RAAN",
                        "value"    => "raan-16",
                        "order"    => 16,
                        "editMode" => false,
                    ],
                    [#4296
                        "id"       => 17,
                        "name"     => "RAAS",
                        "value"    => "raas-17",
                        "order"    => 17,
                        "editMode" => false,
                    ],
                ],
                "slug"     => "departamento",
            ],
            [#4297
                "id"       => 11,
                "name"     => "Teléfono",
                "type"     => "text",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "telefono",
            ],
            [#4298
                "id"       => 12,
                "name"     => "Tutor o Responsable",
                "type"     => "text",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-6 col-lg-6",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "tutor-o-responsable",
            ],
            [#4299
                "name"     => "Fecha de Ingreso",
                "type"     => "date",
                "required" => false,
                "size"     => "col-xs-12 col-sm-6 col-md-4 col-lg-3",
                "tab_id"   => "1",
                "options"  => [],
                "slug"     => "fecha-de-ingreso",
                "id"       => 13,
            ],
        ];


        $form = Form::create([
            'form_name' => 'Formulario General',
        ]);

        $tab = $form->tabs()->create([
            'tab_name' => 'Información General',
        ]);

        collect($fields)->each(function ($field) use ($tab) {
            $tab->fields()->create($field);
        });
    }
}
