<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;

    protected $fillable = [
        'uuid',
        'title',
        'form_id',
        'project_id',
        'goal'
    ];

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($inventory) {
            $inventory->uuid = \Illuminate\Support\Str::uuid();
        });
    }

    public function form()
    {
        return $this->belongsTo(Form::class);
    }

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    public function inventoryItems()
    {
        return $this->hasMany(InventoryItem::class);
    }
}
