<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InventoryItem extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'inventory_id',
        'form_data'
    ];

    protected $casts = [
        'form_data' => 'array'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($inventoryItem) {
            $inventoryItem->uuid = \Illuminate\Support\Str::uuid();
        });
    }

    public function inventory(){
        return $this->belongsTo(Inventory::class);
    }


}
