export const Departamentos = [
    { label: 'Chinandega', value: 'chinandega' },
    { label: 'Leon', value: 'leon' },
    { label: 'Managua', value: 'managua' },
    { label: 'Masaya', value: 'masaya' },
    { label: 'Carazo', value: 'carazo' },
    { label: 'Granada', value: 'granada' },
    { label: 'Rivas', value: 'rivas' },
    { label: 'Nueva Segovia', value: 'nueva-segovia' },
    { label: 'Madriz', value: 'madriz' },
    { label: 'Estelí', value: 'esteli' },
    { label: 'Jinotega', value: 'jinotega' },
    { label: 'Matagalpa', value: 'matagalpa' },
    { label: 'Boaco', value: 'boaco' },
    { label: 'Chontales', value: 'chontales' },
    { label: 'Rio San Juan', value: 'rio-san-juan' },
    { label: 'Atlantico Norte', value: 'atlantico-norte' },
    { label: 'Atlantico Sur', value: 'atlantico-sur' },
]

export const Municipios = [
    [
        { label: 'Chinandega', value: 'chinandega' },
        { label: 'El Viejo', value: 'el-viejo' },
        { label: 'Chichigalpa', value: 'chichigalpa' },
        { label: 'Somotillo', value: 'somotillo' },
        { label: 'Villa Nueva', value: 'villa-nueva' },
        { label: 'San Francisco del Norte', value: 'san-francisco-del-norte' },
        { label: 'San Pedro del Norte', value: 'san-pedro-del-norte' },
        { label: 'Posoltega', value: 'posoltega' },
        { label: 'Corinto', value: 'corinto' },
        { label: 'Puerto Morazán', value: 'puerto-morazan' },
        { label: 'El Realejo', value: 'el-realejo' },
    ],
    [
        { label: 'Leon', value: 'leon' },
        { label: 'Nagarote', value: 'nagarote' },
        { label: 'La Paz Centro', value: 'la-paz-centro' },
        { label: 'El Sauce', value: 'el-sauce' },
        { label: 'Larreynaga', value: 'larreynaga' },
        { label: 'Telica', value: 'telica' },
        { label: 'San José de Achuapa', value: 'san-jose-de-achuapa' },
        { label: 'El Jicaral', value: 'el-jicaral' },
        { label: 'Santa Rosa del Peñon', value: 'santa-rosa-del-penon' },
        { label: 'Quezalguaque', value: 'quezalguaque' },
    ],
    [
        { label: 'Managua', value: 'managua' },
        { label: 'Tipitapa', value: 'tipitapa' },
        { label: 'Ciudad Sandino', value: 'ciudad-sandino' },
        { label: 'San Rafael del Sur', value: 'san-rafael-del-sur' },
        { label: 'Villa el Carmen', value: 'villa-el-carmen' },
        { label: 'Mateare', value: 'mateare' },
        { label: 'Ticuantepe', value: 'ticuantepe' },
        { label: 'El Crucero', value: 'el-crucero' },
        { label: 'San Francisco Libre', value: 'san-francisco-libre' },
    ],
    [
        { label: 'Masaya', value: 'masaya' },
        { label: 'Nindiri', value: 'nindiri' },
        { label: 'La Concepción', value: 'la-concepcion' },
        { label: 'Masatepe', value: 'masatepe' },
        { label: 'Niquinohomo', value: 'niquinohomo' },
        { label: 'Nandasmo', value: 'nandasmo' },
        { label: 'Tisma', value: 'tisma' },
        { label: 'Catarina', value: 'catarina' },
        { label: 'San Juan de Oriente', value: 'san-juan-de-oriente' },
    ],
    [
        { label: 'Diriamba', value: 'diriamba' },
        { label: 'Jinotepe', value: 'jinotepe' },
        { label: 'San Marcos', value: 'san-marcos' },
        { label: 'Santa Teresa', value: 'santa-teresa' },
        { label: 'Dolores', value: 'dolores' },
        { label: 'El Rosario', value: 'el-rosario' },
        { label: 'La Paz de Carazo', value: 'la-paz-de-carazo' },
        { label: 'La Conquista', value: 'la-conquista' },
    ],
    [
        { label: 'Granada', value: 'granada' },
        { label: 'Nandaime', value: 'nandaime' },
        { label: 'Diriomo', value: 'diriomo' },
        { label: 'Diriá', value: 'diria' },
    ],
    [
        { label: 'Rivas', value: 'rivas' },
        { label: 'Tola', value: 'tola' },
        { label: 'Altagracia', value: 'altagracia' },
        { label: 'Belén', value: 'belen' },
        { label: 'San Juan del Sur', value: 'san-juan-del-sur' },
        { label: 'Potosí', value: 'potosi' },
        { label: 'Moyogalpa', value: 'moyogalpa' },
        { label: 'San Jorge', value: 'san-jorge' },
        { label: 'Cárdenas', value: 'c-rdenas' },
        { label: 'Buenos Aires', value: 'buenos-aires' },
    ],
    [
        { label: 'Jalapa', value: 'jalapa' },
        { label: 'Ocotal', value: 'ocotal' },
        { label: 'Quilalí', value: 'quilali' },
        { label: 'El Jícaro', value: 'el-jicaro' },
        { label: 'Wiwilí de Nueva Segovia', value: 'wiwili-de-nueva-segovia' },
        { label: 'Murra', value: 'murra' },
        { label: 'San Fernando', value: 'san-fernando' },
        { label: 'Mozonte', value: 'mozonte' },
        { label: 'Macuelizo', value: 'macuelizo' },
        { label: 'Dipilto', value: 'dipilto' },
        { label: 'Ciudad Antigua', value: 'ciudad-antigua' },
        { label: 'Santa María', value: 'santa-maria' },
    ],
    [
        { label: 'Somoto', value: 'somoto' },
        { label: 'San Juan del Río Coco', value: 'san-juan-del-rio-coco' },
        { label: 'Telpacán', value: 'telpacan' },
        { label: 'San Lucas', value: 'san-lucas' },
        { label: 'Palacaguina', value: 'palacaguina' },
        { label: 'Totogalpa', value: 'totogalpa' },
        { label: 'Yalagüina', value: 'yalaguina' },
        { label: 'San José de Cusmapa', value: 'san-jose-de-cusmapa' },
        { label: 'Las Sabanas', value: 'las-sabanas' },
    ],
    [
        { label: 'Estelí', value: 'esteli' },
        { label: 'Condega', value: 'condega' },
        { label: 'Pueblo Nuevo', value: 'pueblo-nuevo' },
        { label: 'La Trinidad', value: 'la-trinidad' },
        { label: 'San Juan de Limay', value: 'san-juan-de-limay' },
        { label: 'San Nicolás', value: 'san-nicolas' },
    ],
    [
        { label: 'Jinotega', value: 'jinotega' },
        { label: 'Wiwilí de Jinotega', value: 'wiwili-de-jinotega' },
        { label: 'El Cuá', value: 'el-cua' },
        { label: 'San José de Bocay', value: 'san-jose-de-bocay' },
        { label: 'Santa María de Pantasma', value: 'santa-maria-de-pantasma' },
        { label: 'San Sebastián de Yalí', value: 'san-sebastian-de-yali' },
        { label: 'San Rafael del Norte', value: 'san-rafael-del-norte' },
        { label: 'La Concordia', value: 'la-concordia' },
    ],
    [
        { label: 'Matagalpa', value: 'matagalpa' },
        { label: 'El Tuma-La Dalia', value: 'el-tuma-la-dalia' },
        { label: 'Matiguás', value: 'matiguas' },
        { label: 'Ciudad Darío', value: 'ciudad-dario' },
        { label: 'Sébaco', value: 'sebaco' },
        { label: 'Río Blanco', value: 'rio-blanco' },
        { label: 'San Ramón', value: 'san-ramon' },
        { label: 'Rancho Grande', value: 'rancho-grande' },
        { label: 'San Isidro', value: 'san-isidro' },
        { label: 'San Dionisio', value: 'san-dionisio' },
        { label: 'Esquipulas', value: 'esquipulas' },
        { label: 'Muy Muy', value: 'muy-muy' },
        { label: 'Terrabona', value: 'terrabona' },
    ],
    [
        { label: 'Boaco', value: 'boaco' },
        { label: 'Camoapa', value: 'camoapa' },
        { label: 'Teustepe', value: 'teustepe' },
        { label: 'San Lorenzo', value: 'san-lorenzo' },
        { label: 'Santa Lucía', value: 'santa-lucia' },
        { label: 'San José de los Remates', value: 'san-jose-de-los-remates' },
    ],
    [
        { label: 'Juigalpa', value: 'juigalpa' },
        { label: 'Acoyapa', value: 'acoyapa' },
        { label: 'Santo Tomás', value: 'santo-tomas' },
        { label: 'Villa Sandino', value: 'villa-sandino' },
        { label: 'Santo Domingo', value: 'santo-domingo' },
        { label: 'Comalapa', value: 'comalapa' },
        { label: 'La Libertad', value: 'la-libertad' },
        { label: 'San Pedro de Lóvago', value: 'san-pedro-de-lovago' },
        { label: 'El Coral', value: 'el-coral' },
        { label: 'San Francisco de Cuapa', value: 'san-francisco-de-cuapa' },
    ],
    [
        { label: 'San Carlos', value: 'san-carlos' },
        { label: 'El Castillo', value: 'el-castillo' },
        { label: 'San Miguelito', value: 'san-miguelito' },
        { label: 'El Almendro', value: 'el-almendro' },
        { label: 'Morrito', value: 'morrito' },
        { label: 'San Juan de Nicaragua', value: 'san-juan-de-nicaragua' },
    ],
    [
        { label: 'Puerto Cabezas', value: 'puerto-cabezas' },
        { label: 'Siuna', value: 'siuna' },
        { label: 'Waslala', value: 'waslala' },
        { label: 'Waspán', value: 'waspan' },
        { label: 'Mulukukú', value: 'mulukuku' },
        { label: 'Rosita', value: 'rosita' },
        { label: 'Bonanza', value: 'bonanza' },
        { label: 'Prinzapolka', value: 'prinzapolka' },
    ],
    [
        { label: 'Nueva Guinea', value: 'nueva-guinea' },
        { label: 'El Rama', value: 'el-rama' },
        { label: 'Bluefields', value: 'bluefields' },
        { label: 'Paiwas', value: 'paiwas' },
        { label: 'La Cruz de Rio Grande', value: 'la-cruz-de-rio-grande' },
        { label: 'El Tortuguero', value: 'el-tortuguero' },
        { label: 'Muelle de los Bueyes', value: 'muelle-de-los-bueyes' },
        { label: 'El Ayote', value: 'el-ayote' },
        { label: 'Laguna de Perlas', value: 'laguna-de-perlas' },
        { label: 'Kukra - Hill', value: 'kukra-hill' },
        { label: 'Corn Island', value: 'corn-island' },
        {
            label: 'Desembocadura de Rio Grande',
            value: 'desembocadura-de-rio-grande',
        },
    ],
]
